"""
Comprehensive registry of every open-source forensic tool integrated with ForensicX.
Each entry describes installation method, entry-point, and launch command.
"""
from __future__ import annotations

import dataclasses
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT / "tools"


@dataclasses.dataclass
class Tool:
    name: str
    category: str
    description: str
    repo_url: str          # git clone URL (empty = apt/pip/binary)
    install_type: str      # "git" | "apt" | "pip" | "binary" | "manual"
    entry_point: str       # relative path inside tool dir (or command name)
    launch_cmd: list[str]  # command list to launch; {TOOL_DIR} substituted
    license: str
    author: str
    homepage: str
    notes: str = ""

    @property
    def tool_dir(self) -> Path:
        return TOOLS_DIR / self.category / self.name

    @property
    def is_installed(self) -> bool:
        if self.install_type == "apt":
            import shutil
            return shutil.which(self.entry_point) is not None
        if self.install_type == "pip":
            import shutil
            return shutil.which(self.entry_point) is not None
        if self.install_type == "binary":
            ep = TOOLS_DIR / self.category / self.name / self.entry_point
            return ep.exists() and ep.stat().st_size > 0
        # git clone
        ep = self.tool_dir / self.entry_point
        return ep.exists()


# ──────────────────────────────────────────────────────────────────────────────
# MOBILE FORENSICS — Android
# ──────────────────────────────────────────────────────────────────────────────
MOBILE_ANDROID: list[Tool] = [
    Tool(
        name="ALEX",
        category="mobile",
        description="Android Logical Extractor — ADB-based acquisition for Android/FireOS/WearOS",
        repo_url="https://github.com/prosch88/ALEX.git",
        install_type="git",
        entry_point="alex.py",
        launch_cmd=["python3", "{TOOL_DIR}/alex.py"],
        license="GPL-3.0",
        author="Christian Peter (prosch88)",
        homepage="https://github.com/prosch88/ALEX",
    ),
    Tool(
        name="ALEAPP",
        category="mobile",
        description="Android Logs Events And Protobuf Parser — comprehensive artifact parsing",
        repo_url="https://github.com/abrignoni/ALEAPP.git",
        install_type="git",
        entry_point="aleappGUI.py",
        launch_cmd=["python3", "{TOOL_DIR}/aleappGUI.py"],
        license="MIT",
        author="Alexis Brignoni",
        homepage="https://github.com/abrignoni/ALEAPP",
    ),
    Tool(
        name="android_triage",
        category="mobile",
        description="ADB-based Android triage/acquisition script",
        repo_url="https://github.com/RealityNet/android_triage.git",
        install_type="git",
        entry_point="android_triage.sh",
        launch_cmd=["bash", "{TOOL_DIR}/android_triage.sh"],
        license="GPL-3.0",
        author="Mattia Epifani / Giovanni Rattaro",
        homepage="https://github.com/RealityNet/android_triage",
    ),
    Tool(
        name="MVT",
        category="mobile",
        description="Mobile Verification Toolkit — detect spyware/stalkerware on Android/iOS",
        repo_url="https://github.com/mvt-project/mvt.git",
        install_type="git",
        entry_point="mvt/cli.py",
        launch_cmd=["python3", "-m", "mvt"],
        license="MVT License 1.1",
        author="Amnesty International Security Lab",
        homepage="https://github.com/mvt-project/mvt",
        notes="Detects Pegasus and other spyware indicators",
    ),
    Tool(
        name="Andriller",
        category="mobile",
        description="Android forensics tool — app data extraction without root",
        repo_url="https://github.com/den4uk/andriller.git",
        install_type="git",
        entry_point="andriller/__main__.py",
        launch_cmd=["python3", "-m", "andriller"],
        license="MIT",
        author="Den Yakovlev",
        homepage="https://github.com/den4uk/andriller",
    ),
    Tool(
        name="apktool",
        category="mobile",
        description="Reverse engineering Android APK files",
        repo_url="",
        install_type="binary",
        entry_point="apktool.jar",
        launch_cmd=["java", "-jar", "{TOOL_DIR}/apktool.jar"],
        license="Apache-2.0",
        author="Connor Tumbleson / Ryszard Wiśniewski",
        homepage="https://apktool.org",
    ),
    Tool(
        name="jadx",
        category="mobile",
        description="DEX to Java decompiler — analyze Android APKs",
        repo_url="https://github.com/skylot/jadx.git",
        install_type="git",
        entry_point="build/jadx/bin/jadx-gui",
        launch_cmd=["{TOOL_DIR}/build/jadx/bin/jadx-gui"],
        license="Apache-2.0",
        author="Skylot",
        homepage="https://github.com/skylot/jadx",
    ),
    Tool(
        name="dex2jar",
        category="mobile",
        description="Convert Android DEX bytecode to JAR",
        repo_url="https://github.com/pxb1988/dex2jar.git",
        install_type="git",
        entry_point="d2j-dex2jar.sh",
        launch_cmd=["bash", "{TOOL_DIR}/d2j-dex2jar.sh"],
        license="Apache-2.0",
        author="Panxiaobo",
        homepage="https://github.com/pxb1988/dex2jar",
    ),
    Tool(
        name="AEX",
        category="mobile",
        description="Android Evidence Extractor — forensic triage via ADB",
        repo_url="https://github.com/jfarley248/MEAT.git",
        install_type="git",
        entry_point="meat.py",
        launch_cmd=["python3", "{TOOL_DIR}/meat.py"],
        license="MIT",
        author="Josh Farley",
        homepage="https://github.com/jfarley248/MEAT",
    ),
    Tool(
        name="VLEAPP",
        category="mobile",
        description="Vehicle Logs Events And Protobuf Parser",
        repo_url="https://github.com/abrignoni/VLEAPP.git",
        install_type="git",
        entry_point="vleappGUI.py",
        launch_cmd=["python3", "{TOOL_DIR}/vleappGUI.py"],
        license="MIT",
        author="Alexis Brignoni",
        homepage="https://github.com/abrignoni/VLEAPP",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# MOBILE FORENSICS — iOS / Apple
# ──────────────────────────────────────────────────────────────────────────────
MOBILE_IOS: list[Tool] = [
    Tool(
        name="UFADE",
        category="mobile",
        description="Universal Forensic Apple Device Extractor — logical/PRFS acquisition",
        repo_url="https://github.com/prosch88/UFADE.git",
        install_type="git",
        entry_point="ufade.py",
        launch_cmd=["python3", "{TOOL_DIR}/ufade.py"],
        license="GPL-3.0",
        author="Christian Peter (prosch88)",
        homepage="https://github.com/prosch88/UFADE",
        notes="Requires Python 3.11; macOS or Linux with libimobiledevice",
    ),
    Tool(
        name="iLEAPP",
        category="mobile",
        description="iOS Logs Events And Protobuf Parser — iOS artifact extraction",
        repo_url="https://github.com/abrignoni/iLEAPP.git",
        install_type="git",
        entry_point="ileappGUI.py",
        launch_cmd=["python3", "{TOOL_DIR}/ileappGUI.py"],
        license="MIT",
        author="Alexis Brignoni",
        homepage="https://github.com/abrignoni/iLEAPP",
    ),
    Tool(
        name="RLEAPP",
        category="mobile",
        description="Roku Logs Events And Protobuf Parser",
        repo_url="https://github.com/abrignoni/RLEAPP.git",
        install_type="git",
        entry_point="rleappGUI.py",
        launch_cmd=["python3", "{TOOL_DIR}/rleappGUI.py"],
        license="MIT",
        author="Alexis Brignoni",
        homepage="https://github.com/abrignoni/RLEAPP",
    ),
    Tool(
        name="libimobiledevice",
        category="mobile",
        description="iOS device communication library and tools",
        repo_url="",
        install_type="apt",
        entry_point="ideviceinfo",
        launch_cmd=["ideviceinfo"],
        license="LGPL-2.1",
        author="libimobiledevice contributors",
        homepage="https://libimobiledevice.org",
    ),
    Tool(
        name="idevice-backup",
        category="mobile",
        description="iOS backup extraction using libimobiledevice",
        repo_url="https://github.com/jsharkey13/iphone_backup_decrypt.git",
        install_type="git",
        entry_point="iphone_backup_decrypt/__init__.py",
        launch_cmd=["python3", "-m", "iphone_backup_decrypt"],
        license="MIT",
        author="James Sharkey",
        homepage="https://github.com/jsharkey13/iphone_backup_decrypt",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# DISK & IMAGE FORENSICS
# ──────────────────────────────────────────────────────────────────────────────
DISK_TOOLS: list[Tool] = [
    Tool(
        name="autopsy",
        category="disk",
        description="Autopsy — GUI forensic platform built on The Sleuth Kit",
        repo_url="https://github.com/sleuthkit/autopsy.git",
        install_type="apt",
        entry_point="autopsy",
        launch_cmd=["autopsy"],
        license="Apache-2.0 / other",
        author="Sleuth Kit Labs",
        homepage="https://www.autopsy.com",
        notes="Install via apt: apt install autopsy",
    ),
    Tool(
        name="sleuthkit",
        category="disk",
        description="The Sleuth Kit — command-line disk image analysis (fls, icat, mmls…)",
        repo_url="https://github.com/sleuthkit/sleuthkit.git",
        install_type="apt",
        entry_point="fls",
        launch_cmd=["fls"],
        license="IBM/CPL-1.0/GPL-2.0",
        author="Brian Carrier",
        homepage="https://www.sleuthkit.org",
    ),
    Tool(
        name="bulk_extractor",
        category="disk",
        description="Extracts features (emails, URLs, CC numbers) from disk images without mounting",
        repo_url="https://github.com/simsong/bulk_extractor.git",
        install_type="apt",
        entry_point="bulk_extractor",
        launch_cmd=["bulk_extractor"],
        license="Public Domain",
        author="Simson Garfinkel",
        homepage="https://github.com/simsong/bulk_extractor",
    ),
    Tool(
        name="scalpel",
        category="disk",
        description="File carver — recovers deleted files from disk images",
        repo_url="https://github.com/sleuthkit/scalpel.git",
        install_type="apt",
        entry_point="scalpel",
        launch_cmd=["scalpel"],
        license="GPL-2.0",
        author="Golden Richard / Vassil Roussev",
        homepage="https://github.com/sleuthkit/scalpel",
    ),
    Tool(
        name="foremost",
        category="disk",
        description="File recovery based on headers/footers — classic file carver",
        repo_url="",
        install_type="apt",
        entry_point="foremost",
        launch_cmd=["foremost"],
        license="Public Domain",
        author="Jesse Kornblum / Kris Kendall",
        homepage="http://foremost.sourceforge.net",
    ),
    Tool(
        name="photorec",
        category="disk",
        description="PhotoRec — file recovery from disk images and storage media",
        repo_url="",
        install_type="apt",
        entry_point="photorec",
        launch_cmd=["photorec"],
        license="GPL-2.0",
        author="Christophe Grenier",
        homepage="https://www.cgsecurity.org/wiki/PhotoRec",
    ),
    Tool(
        name="testdisk",
        category="disk",
        description="TestDisk — partition recovery and disk repair",
        repo_url="",
        install_type="apt",
        entry_point="testdisk",
        launch_cmd=["testdisk"],
        license="GPL-2.0",
        author="Christophe Grenier",
        homepage="https://www.cgsecurity.org/wiki/TestDisk",
    ),
    Tool(
        name="dc3dd",
        category="disk",
        description="Forensic imaging — enhanced dd with hashing and progress",
        repo_url="",
        install_type="apt",
        entry_point="dc3dd",
        launch_cmd=["dc3dd"],
        license="GPL-3.0",
        author="DoD Cyber Crime Center",
        homepage="https://sourceforge.net/projects/dc3dd/",
    ),
    Tool(
        name="ewf-tools",
        category="disk",
        description="Expert Witness Format (E01) tools — mount and analyze EWF images",
        repo_url="",
        install_type="apt",
        entry_point="ewfinfo",
        launch_cmd=["ewfinfo"],
        license="LGPL-3.0",
        author="Joachim Metz",
        homepage="https://github.com/libyal/libewf",
    ),
    Tool(
        name="xmount",
        category="disk",
        description="Mount disk images (dd/E01/AFF) as block devices",
        repo_url="",
        install_type="apt",
        entry_point="xmount",
        launch_cmd=["xmount"],
        license="GPL-3.0",
        author="Gillen Daniel",
        homepage="https://www.pinguin.lu/index.php",
    ),
    Tool(
        name="afflib-tools",
        category="disk",
        description="Advanced Forensic Format (AFF) disk image tools",
        repo_url="",
        install_type="apt",
        entry_point="affinfo",
        launch_cmd=["affinfo"],
        license="BSD",
        author="Simson Garfinkel",
        homepage="https://github.com/sshock/AFFLIBv3",
    ),
    Tool(
        name="ddrescue",
        category="disk",
        description="GNU ddrescue — data recovery from damaged media",
        repo_url="",
        install_type="apt",
        entry_point="ddrescue",
        launch_cmd=["ddrescue"],
        license="GPL-2.0",
        author="Antonio Diaz",
        homepage="https://www.gnu.org/software/ddrescue/",
    ),
    Tool(
        name="guymager",
        category="disk",
        description="GUI forensic imager — acquire disk images with hashing",
        repo_url="",
        install_type="apt",
        entry_point="guymager",
        launch_cmd=["guymager"],
        license="GPL-2.0",
        author="Guy Voncken",
        homepage="https://guymager.sourceforge.io",
    ),
    Tool(
        name="fdupes",
        category="disk",
        description="Find duplicate files across filesystem",
        repo_url="",
        install_type="apt",
        entry_point="fdupes",
        launch_cmd=["fdupes"],
        license="MIT",
        author="Adrian Lopez",
        homepage="https://github.com/adrianlopezroche/fdupes",
    ),
    Tool(
        name="ssdeep",
        category="disk",
        description="Fuzzy hash tool for file similarity comparison",
        repo_url="",
        install_type="apt",
        entry_point="ssdeep",
        launch_cmd=["ssdeep"],
        license="GPL-2.0",
        author="Jesse Kornblum",
        homepage="https://ssdeep-project.github.io",
    ),
    Tool(
        name="hashdeep",
        category="disk",
        description="Compute and audit hash sets (MD5/SHA-1/SHA-256/Tiger/Whirlpool)",
        repo_url="",
        install_type="apt",
        entry_point="hashdeep",
        launch_cmd=["hashdeep"],
        license="Public Domain",
        author="Jesse Kornblum",
        homepage="https://github.com/jessek/hashdeep",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# MEMORY FORENSICS
# ──────────────────────────────────────────────────────────────────────────────
MEMORY_TOOLS: list[Tool] = [
    Tool(
        name="volatility3",
        category="memory",
        description="Volatility 3 — memory forensics framework",
        repo_url="https://github.com/volatilityfoundation/volatility3.git",
        install_type="git",
        entry_point="vol.py",
        launch_cmd=["python3", "{TOOL_DIR}/vol.py"],
        license="Volatility Software License 1.0",
        author="Volatility Foundation",
        homepage="https://github.com/volatilityfoundation/volatility3",
    ),
    Tool(
        name="volatility2",
        category="memory",
        description="Volatility 2 — classic memory forensics framework",
        repo_url="https://github.com/volatilityfoundation/volatility.git",
        install_type="git",
        entry_point="vol.py",
        launch_cmd=["python3", "{TOOL_DIR}/vol.py"],
        license="GPL-2.0",
        author="Volatility Foundation",
        homepage="https://github.com/volatilityfoundation/volatility",
        notes="Use Volatility 3 for new work; v2 retained for legacy profiles",
    ),
    Tool(
        name="LiME",
        category="memory",
        description="Linux Memory Extractor — loadable kernel module for RAM acquisition",
        repo_url="https://github.com/504ensicsLabs/LiME.git",
        install_type="git",
        entry_point="src/Makefile",
        launch_cmd=["make", "-C", "{TOOL_DIR}/src"],
        license="GPL-2.0",
        author="Joe Sylve",
        homepage="https://github.com/504ensicsLabs/LiME",
        notes="Requires kernel headers to build",
    ),
    Tool(
        name="avml",
        category="memory",
        description="Acquire Volatile Memory for Linux — Microsoft tool",
        repo_url="https://github.com/microsoft/avml.git",
        install_type="git",
        entry_point="avml",
        launch_cmd=["{TOOL_DIR}/avml"],
        license="MIT",
        author="Microsoft",
        homepage="https://github.com/microsoft/avml",
    ),
    Tool(
        name="MemProcFS",
        category="memory",
        description="Memory Process Filesystem — virtual filesystem for memory analysis",
        repo_url="https://github.com/ufrisk/MemProcFS.git",
        install_type="git",
        entry_point="MemProcFS",
        launch_cmd=["{TOOL_DIR}/MemProcFS"],
        license="AGPL-3.0",
        author="Ulf Frisk",
        homepage="https://github.com/ufrisk/MemProcFS",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# LOG / TIMELINE ANALYSIS
# ──────────────────────────────────────────────────────────────────────────────
LOG_TOOLS: list[Tool] = [
    Tool(
        name="plaso",
        category="logs",
        description="log2timeline/plaso — super timeline generation from many log sources",
        repo_url="https://github.com/log2timeline/plaso.git",
        install_type="pip",
        entry_point="log2timeline.py",
        launch_cmd=["log2timeline.py"],
        license="Apache-2.0",
        author="Kristinn Gudjonsson / plaso contributors",
        homepage="https://github.com/log2timeline/plaso",
    ),
    Tool(
        name="timesketch",
        category="logs",
        description="Timesketch — collaborative timeline analysis web app",
        repo_url="https://github.com/google/timesketch.git",
        install_type="git",
        entry_point="tsctl",
        launch_cmd=["tsctl"],
        license="Apache-2.0",
        author="Google",
        homepage="https://timesketch.org",
        notes="Docker deployment recommended",
    ),
    Tool(
        name="chainsaw",
        category="logs",
        description="Rapidly search and hunt through Windows Event Logs",
        repo_url="https://github.com/WithSecureLabs/chainsaw.git",
        install_type="binary",
        entry_point="chainsaw",
        launch_cmd=["{TOOL_DIR}/chainsaw"],
        license="GPL-3.0",
        author="WithSecure Labs",
        homepage="https://github.com/WithSecureLabs/chainsaw",
    ),
    Tool(
        name="hayabusa",
        category="logs",
        description="Windows Event Log threat hunting and timeline tool",
        repo_url="https://github.com/Yamato-Security/hayabusa.git",
        install_type="binary",
        entry_point="hayabusa",
        launch_cmd=["{TOOL_DIR}/hayabusa"],
        license="AGPL-3.0",
        author="Yamato Security",
        homepage="https://github.com/Yamato-Security/hayabusa",
    ),
    Tool(
        name="sigma",
        category="logs",
        description="Sigma — generic signature format for SIEM rule conversion",
        repo_url="https://github.com/SigmaHQ/sigma.git",
        install_type="git",
        entry_point="tools/sigma/main.py",
        launch_cmd=["python3", "{TOOL_DIR}/tools/sigma/main.py"],
        license="LGPL-2.1",
        author="Florian Roth / Thomas Patzke",
        homepage="https://github.com/SigmaHQ/sigma",
    ),
    Tool(
        name="evtx",
        category="logs",
        description="EVTX parser — read Windows Event Log files from Linux",
        repo_url="https://github.com/omerbenamram/evtx.git",
        install_type="binary",
        entry_point="evtx_dump",
        launch_cmd=["{TOOL_DIR}/evtx_dump"],
        license="MIT",
        author="Omer Ben-Amram",
        homepage="https://github.com/omerbenamram/evtx",
    ),
    Tool(
        name="LogonTracer",
        category="logs",
        description="Investigate malicious logon events via Windows Event Logs",
        repo_url="https://github.com/JPCERTCC/LogonTracer.git",
        install_type="git",
        entry_point="logontracer.py",
        launch_cmd=["python3", "{TOOL_DIR}/logontracer.py"],
        license="MIT",
        author="JPCERT/CC",
        homepage="https://github.com/JPCERTCC/LogonTracer",
    ),
    Tool(
        name="UAC",
        category="logs",
        description="Unix-like Artifacts Collector — macOS/Linux/AIX triage collection",
        repo_url="https://github.com/tclahr/uac.git",
        install_type="git",
        entry_point="uac",
        launch_cmd=["bash", "{TOOL_DIR}/uac"],
        license="Apache-2.0",
        author="Thiago Canovas",
        homepage="https://github.com/tclahr/uac",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# NETWORK FORENSICS
# ──────────────────────────────────────────────────────────────────────────────
NETWORK_TOOLS: list[Tool] = [
    Tool(
        name="wireshark",
        category="network",
        description="Wireshark — network protocol analyzer",
        repo_url="",
        install_type="apt",
        entry_point="wireshark",
        launch_cmd=["wireshark"],
        license="GPL-2.0",
        author="Gerald Combs",
        homepage="https://www.wireshark.org",
    ),
    Tool(
        name="tshark",
        category="network",
        description="tshark — terminal-based packet capture/analysis (Wireshark CLI)",
        repo_url="",
        install_type="apt",
        entry_point="tshark",
        launch_cmd=["tshark"],
        license="GPL-2.0",
        author="Gerald Combs",
        homepage="https://www.wireshark.org",
    ),
    Tool(
        name="NetworkMiner",
        category="network",
        description="Network forensic analyzer — passive capture and artifact extraction",
        repo_url="https://github.com/rnesselrath/NetworkMiner.git",
        install_type="git",
        entry_point="NetworkMiner.exe",
        launch_cmd=["mono", "{TOOL_DIR}/NetworkMiner.exe"],
        license="GPL-2.0",
        author="Erik Hjelmvik / Netresec",
        homepage="https://www.netresec.com/?page=NetworkMiner",
        notes="Free edition only; requires Mono on Linux",
    ),
    Tool(
        name="xplico",
        category="network",
        description="Network forensic analysis — extract data from pcap captures",
        repo_url="https://github.com/xplico/xplico.git",
        install_type="apt",
        entry_point="xplico",
        launch_cmd=["xplico"],
        license="GPL-2.0",
        author="Gianluca Costa",
        homepage="https://www.xplico.org",
    ),
    Tool(
        name="ngrep",
        category="network",
        description="Network grep — pattern matching for packet payloads",
        repo_url="",
        install_type="apt",
        entry_point="ngrep",
        launch_cmd=["ngrep"],
        license="BSD",
        author="Jordan Ritter",
        homepage="https://github.com/jpr5/ngrep",
    ),
    Tool(
        name="tcpdump",
        category="network",
        description="CLI packet capture — the standard Unix network sniffer",
        repo_url="",
        install_type="apt",
        entry_point="tcpdump",
        launch_cmd=["tcpdump"],
        license="BSD",
        author="Van Jacobson / others",
        homepage="https://www.tcpdump.org",
    ),
    Tool(
        name="zeek",
        category="network",
        description="Zeek (Bro) — powerful network analysis framework",
        repo_url="https://github.com/zeek/zeek.git",
        install_type="apt",
        entry_point="zeek",
        launch_cmd=["zeek"],
        license="BSD",
        author="The Zeek Project",
        homepage="https://zeek.org",
    ),
    Tool(
        name="tcpflow",
        category="network",
        description="Reconstructs TCP streams from packet captures",
        repo_url="",
        install_type="apt",
        entry_point="tcpflow",
        launch_cmd=["tcpflow"],
        license="GPL-3.0",
        author="Simson Garfinkel",
        homepage="https://github.com/simsong/tcpflow",
    ),
    Tool(
        name="dnscat2",
        category="network",
        description="DNS forensics — analyze DNS traffic/tunneling",
        repo_url="https://github.com/iagox86/dnscat2.git",
        install_type="git",
        entry_point="server/dnscat2.rb",
        launch_cmd=["ruby", "{TOOL_DIR}/server/dnscat2.rb"],
        license="BSD",
        author="Ron Bowes",
        homepage="https://github.com/iagox86/dnscat2",
    ),
    Tool(
        name="netflow-tools",
        category="network",
        description="SiLK / nfdump — NetFlow/IPFIX collection and analysis",
        repo_url="",
        install_type="apt",
        entry_point="nfdump",
        launch_cmd=["nfdump"],
        license="GPL-2.0",
        author="CERT NetSA",
        homepage="https://tools.netsa.cert.org/silk/",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# FILE / ARTIFACT ANALYSIS
# ──────────────────────────────────────────────────────────────────────────────
ARTIFACT_TOOLS: list[Tool] = [
    Tool(
        name="exiftool",
        category="artifacts",
        description="ExifTool — read/write metadata in images, video, audio, PDFs",
        repo_url="",
        install_type="apt",
        entry_point="exiftool",
        launch_cmd=["exiftool"],
        license="Perl Artistic License",
        author="Phil Harvey",
        homepage="https://exiftool.org",
    ),
    Tool(
        name="regripper",
        category="artifacts",
        description="RegRipper — Windows Registry forensics/parsing",
        repo_url="https://github.com/keydet89/RegRipper3.0.git",
        install_type="git",
        entry_point="rip.pl",
        launch_cmd=["perl", "{TOOL_DIR}/rip.pl"],
        license="GPL-2.0",
        author="H. Carvey",
        homepage="https://github.com/keydet89/RegRipper3.0",
    ),
    Tool(
        name="hindsight",
        category="artifacts",
        description="Chrome browser forensics — history, cookies, cache, downloads",
        repo_url="https://github.com/obsidianforensics/hindsight.git",
        install_type="git",
        entry_point="hindsight.py",
        launch_cmd=["python3", "{TOOL_DIR}/hindsight.py"],
        license="Apache-2.0",
        author="Ryan Benson",
        homepage="https://github.com/obsidianforensics/hindsight",
    ),
    Tool(
        name="pdfid",
        category="artifacts",
        description="PDF analysis — identify suspicious keywords in PDFs",
        repo_url="https://github.com/DidierStevens/DidierStevensSuite.git",
        install_type="git",
        entry_point="pdfid.py",
        launch_cmd=["python3", "{TOOL_DIR}/pdfid.py"],
        license="Public Domain",
        author="Didier Stevens",
        homepage="https://github.com/DidierStevens/DidierStevensSuite",
    ),
    Tool(
        name="oletools",
        category="artifacts",
        description="Python tools for OLE2 / MS Office document analysis",
        repo_url="https://github.com/decalage2/oletools.git",
        install_type="pip",
        entry_point="olevba",
        launch_cmd=["olevba"],
        license="BSD",
        author="Philippe Lagadec",
        homepage="https://github.com/decalage2/oletools",
    ),
    Tool(
        name="peepdf",
        category="artifacts",
        description="PDF analysis framework with scripting support",
        repo_url="https://github.com/jesparza/peepdf.git",
        install_type="git",
        entry_point="peepdf.py",
        launch_cmd=["python3", "{TOOL_DIR}/peepdf.py"],
        license="GPL-2.0",
        author="Jose Miguel Esparza",
        homepage="https://github.com/jesparza/peepdf",
    ),
    Tool(
        name="orc",
        category="artifacts",
        description="ORC (Outbreak Response Collection) — Windows artifact collector",
        repo_url="https://github.com/dfir-orc/dfir-orc.git",
        install_type="git",
        entry_point="ORC.exe",
        launch_cmd=["wine", "{TOOL_DIR}/ORC.exe"],
        license="Apache-2.0",
        author="ANSSI",
        homepage="https://github.com/dfir-orc/dfir-orc",
    ),
    Tool(
        name="rekall",
        category="artifacts",
        description="Rekall memory forensics framework (Volatility fork)",
        repo_url="https://github.com/google/rekall.git",
        install_type="pip",
        entry_point="rekal",
        launch_cmd=["rekal"],
        license="GPL-2.0",
        author="Google / Michael Cohen",
        homepage="https://github.com/google/rekall",
        notes="Legacy; use Volatility 3 for active development",
    ),
    Tool(
        name="FLOSS",
        category="artifacts",
        description="FireEye FLARE FLOSS — automatically de-obfuscate strings from malware",
        repo_url="https://github.com/mandiant/flare-floss.git",
        install_type="git",
        entry_point="floss/main.py",
        launch_cmd=["python3", "{TOOL_DIR}/floss/main.py"],
        license="Apache-2.0",
        author="Mandiant FLARE",
        homepage="https://github.com/mandiant/flare-floss",
    ),
    Tool(
        name="binwalk",
        category="artifacts",
        description="Firmware analysis and extraction tool",
        repo_url="https://github.com/ReFirmLabs/binwalk.git",
        install_type="git",
        entry_point="src/binwalk/__main__.py",
        launch_cmd=["python3", "-m", "binwalk"],
        license="MIT",
        author="Craig Heffner / ReFirm Labs",
        homepage="https://github.com/ReFirmLabs/binwalk",
    ),
    Tool(
        name="strings2",
        category="artifacts",
        description="Extract printable strings from binary files",
        repo_url="",
        install_type="apt",
        entry_point="strings",
        launch_cmd=["strings"],
        license="GPL-3.0",
        author="GNU binutils",
        homepage="https://www.gnu.org/software/binutils/",
    ),
    Tool(
        name="fileinfo",
        category="artifacts",
        description="file + hexdump — basic binary triage (type identification)",
        repo_url="",
        install_type="apt",
        entry_point="file",
        launch_cmd=["file"],
        license="BSD",
        author="Ian Darwin",
        homepage="https://darwinsys.com/file/",
    ),
    Tool(
        name="steghide",
        category="artifacts",
        description="Steganography — embed/detect hidden data in JPEG/BMP/WAV",
        repo_url="",
        install_type="apt",
        entry_point="steghide",
        launch_cmd=["steghide"],
        license="GPL-2.0",
        author="Stefan Hetzl",
        homepage="https://steghide.sourceforge.net",
    ),
    Tool(
        name="zsteg",
        category="artifacts",
        description="Detect hidden data in PNG/BMP (LSB steganography)",
        repo_url="https://github.com/zed-0xff/zsteg.git",
        install_type="git",
        entry_point="bin/zsteg",
        launch_cmd=["ruby", "{TOOL_DIR}/bin/zsteg"],
        license="MIT",
        author="Zed-0xff",
        homepage="https://github.com/zed-0xff/zsteg",
    ),
    Tool(
        name="StegExpose",
        category="artifacts",
        description="Steganalysis — batch LSB steganography detection",
        repo_url="https://github.com/b3dk7/StegExpose.git",
        install_type="git",
        entry_point="StegExpose.jar",
        launch_cmd=["java", "-jar", "{TOOL_DIR}/StegExpose.jar"],
        license="MIT",
        author="b3dk7",
        homepage="https://github.com/b3dk7/StegExpose",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# PASSWORD & HASH ANALYSIS
# ──────────────────────────────────────────────────────────────────────────────
PASSWORD_TOOLS: list[Tool] = [
    Tool(
        name="hashcat",
        category="password",
        description="Hashcat — world's fastest password recovery / GPU hash cracking",
        repo_url="https://github.com/hashcat/hashcat.git",
        install_type="apt",
        entry_point="hashcat",
        launch_cmd=["hashcat"],
        license="MIT",
        author="Jens Steube",
        homepage="https://hashcat.net",
    ),
    Tool(
        name="john",
        category="password",
        description="John the Ripper — traditional password cracker",
        repo_url="https://github.com/openwall/john.git",
        install_type="apt",
        entry_point="john",
        launch_cmd=["john"],
        license="GPL-2.0",
        author="Solar Designer",
        homepage="https://www.openwall.com/john/",
    ),
    Tool(
        name="hashid",
        category="password",
        description="Identify hash type from its format",
        repo_url="https://github.com/psypanda/hashID.git",
        install_type="pip",
        entry_point="hashid",
        launch_cmd=["hashid"],
        license="GPL-3.0",
        author="psypanda",
        homepage="https://github.com/psypanda/hashID",
    ),
    Tool(
        name="fcrackzip",
        category="password",
        description="ZIP password cracker",
        repo_url="",
        install_type="apt",
        entry_point="fcrackzip",
        launch_cmd=["fcrackzip"],
        license="GPL-2.0",
        author="Marc Lehmann",
        homepage="http://oldhome.schmorp.de/marc/fcrackzip.html",
    ),
    Tool(
        name="pdfcrack",
        category="password",
        description="PDF password recovery",
        repo_url="",
        install_type="apt",
        entry_point="pdfcrack",
        launch_cmd=["pdfcrack"],
        license="GPL-2.0",
        author="Henrik Stokseth",
        homepage="https://sourceforge.net/projects/pdfcrack/",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# MALWARE ANALYSIS / REVERSE ENGINEERING
# ──────────────────────────────────────────────────────────────────────────────
MALWARE_TOOLS: list[Tool] = [
    Tool(
        name="ghidra",
        category="malware",
        description="Ghidra — NSA reverse engineering framework",
        repo_url="https://github.com/NationalSecurityAgency/ghidra.git",
        install_type="binary",
        entry_point="ghidraRun",
        launch_cmd=["{TOOL_DIR}/ghidraRun"],
        license="Apache-2.0",
        author="NSA Research Directorate",
        homepage="https://ghidra-sre.org",
        notes="Requires Java 17+; download binary from GitHub releases",
    ),
    Tool(
        name="radare2",
        category="malware",
        description="Radare2 — open-source reverse engineering framework",
        repo_url="https://github.com/radareorg/radare2.git",
        install_type="apt",
        entry_point="r2",
        launch_cmd=["r2"],
        license="LGPL-3.0",
        author="pancake / radare2 community",
        homepage="https://www.radare.org",
    ),
    Tool(
        name="cutter",
        category="malware",
        description="Cutter — GUI frontend for radare2",
        repo_url="https://github.com/rizinorg/cutter.git",
        install_type="binary",
        entry_point="Cutter",
        launch_cmd=["{TOOL_DIR}/Cutter"],
        license="GPL-3.0",
        author="Rizin org",
        homepage="https://cutter.re",
    ),
    Tool(
        name="yara",
        category="malware",
        description="YARA — pattern matching for malware classification",
        repo_url="https://github.com/VirusTotal/yara.git",
        install_type="apt",
        entry_point="yara",
        launch_cmd=["yara"],
        license="BSD-3-Clause",
        author="Victor M. Alvarez / VirusTotal",
        homepage="https://virustotal.github.io/yara/",
    ),
    Tool(
        name="clamav",
        category="malware",
        description="ClamAV — open-source antivirus/malware scanner",
        repo_url="",
        install_type="apt",
        entry_point="clamscan",
        launch_cmd=["clamscan"],
        license="GPL-2.0",
        author="Cisco Talos",
        homepage="https://www.clamav.net",
    ),
    Tool(
        name="pestudio",
        category="malware",
        description="PE analysis — static malware initial assessment (Windows tool)",
        repo_url="",
        install_type="manual",
        entry_point="pestudio.exe",
        launch_cmd=["wine", "{TOOL_DIR}/pestudio.exe"],
        license="Freeware",
        author="Marc Ochsenmeier",
        homepage="https://www.winitor.com",
        notes="Download from official site; freeware",
    ),
    Tool(
        name="pefile",
        category="malware",
        description="Python PE library — parse/analyze Windows PE files",
        repo_url="https://github.com/erocarrera/pefile.git",
        install_type="pip",
        entry_point="pefile",
        launch_cmd=["python3", "-c", "import pefile; print('pefile available')"],
        license="MIT",
        author="Ero Carrera",
        homepage="https://github.com/erocarrera/pefile",
    ),
    Tool(
        name="die",
        category="malware",
        description="Detect It Easy — identify packer/compiler/linker",
        repo_url="https://github.com/horsicq/Detect-It-Easy.git",
        install_type="binary",
        entry_point="die",
        launch_cmd=["{TOOL_DIR}/die"],
        license="MIT",
        author="horsicq",
        homepage="https://github.com/horsicq/Detect-It-Easy",
    ),
    Tool(
        name="capa",
        category="malware",
        description="capa — identify capabilities in executables (Mandiant FLARE)",
        repo_url="https://github.com/mandiant/capa.git",
        install_type="git",
        entry_point="capa/main.py",
        launch_cmd=["python3", "{TOOL_DIR}/capa/main.py"],
        license="Apache-2.0",
        author="Mandiant FLARE",
        homepage="https://github.com/mandiant/capa",
    ),
    Tool(
        name="speakeasy",
        category="malware",
        description="Windows emulator for malware analysis (Mandiant)",
        repo_url="https://github.com/mandiant/speakeasy.git",
        install_type="git",
        entry_point="speakeasy/main.py",
        launch_cmd=["python3", "{TOOL_DIR}/speakeasy/main.py"],
        license="MIT",
        author="Mandiant",
        homepage="https://github.com/mandiant/speakeasy",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# INCIDENT RESPONSE
# ──────────────────────────────────────────────────────────────────────────────
IR_TOOLS: list[Tool] = [
    Tool(
        name="velociraptor",
        category="ir",
        description="Velociraptor — endpoint visibility and live forensic collection",
        repo_url="https://github.com/Velocidex/velociraptor.git",
        install_type="binary",
        entry_point="velociraptor",
        launch_cmd=["{TOOL_DIR}/velociraptor"],
        license="AGPL-3.0",
        author="Velocidex Enterprises",
        homepage="https://www.velocidex.com",
    ),
    Tool(
        name="osquery",
        category="ir",
        description="osquery — SQL interface to OS state for live incident response",
        repo_url="",
        install_type="apt",
        entry_point="osqueryi",
        launch_cmd=["osqueryi"],
        license="Apache-2.0",
        author="Meta",
        homepage="https://osquery.io",
    ),
    Tool(
        name="GRR",
        category="ir",
        description="GRR Rapid Response — remote forensics and incident response",
        repo_url="https://github.com/google/grr.git",
        install_type="git",
        entry_point="grr/server/grr_server.py",
        launch_cmd=["python3", "{TOOL_DIR}/grr/server/grr_server.py"],
        license="Apache-2.0",
        author="Google",
        homepage="https://github.com/google/grr",
        notes="Server/client architecture; see docs for deployment",
    ),
    Tool(
        name="crowdstrike-forensics",
        category="ir",
        description="CrowdStrike Forensics (KAPE alternative) — artifact collection",
        repo_url="https://github.com/CrowdStrike/forensics.git",
        install_type="git",
        entry_point="forensics.py",
        launch_cmd=["python3", "{TOOL_DIR}/forensics.py"],
        license="MIT",
        author="CrowdStrike",
        homepage="https://github.com/CrowdStrike/forensics",
    ),
    Tool(
        name="KAPE",
        category="ir",
        description="Kroll Artifact Parser and Extractor — triage/collection (Windows)",
        repo_url="",
        install_type="manual",
        entry_point="kape.exe",
        launch_cmd=["wine", "{TOOL_DIR}/kape.exe"],
        license="Proprietary (freeware)",
        author="Kroll / Eric Zimmermann",
        homepage="https://www.kroll.com/kape",
        notes="Download from Kroll site; freeware for non-commercial use",
    ),
    Tool(
        name="fastir",
        category="ir",
        description="FastIR Collector — artifact collection for incident response",
        repo_url="https://github.com/SekoiaLab/Fastir_Collector.git",
        install_type="git",
        entry_point="fastIR_gui.py",
        launch_cmd=["python3", "{TOOL_DIR}/fastIR_gui.py"],
        license="GPL-3.0",
        author="SekoiaLab",
        homepage="https://github.com/SekoiaLab/Fastir_Collector",
    ),
    Tool(
        name="ir-rescue",
        category="ir",
        description="Windows IR triage collection script",
        repo_url="https://github.com/diogo-fernan/ir-rescue.git",
        install_type="git",
        entry_point="ir-rescue.bat",
        launch_cmd=["bash", "{TOOL_DIR}/ir-rescue.bat"],
        license="MIT",
        author="Diogo Fernan",
        homepage="https://github.com/diogo-fernan/ir-rescue",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# OSINT
# ──────────────────────────────────────────────────────────────────────────────
OSINT_TOOLS: list[Tool] = [
    Tool(
        name="spiderfoot",
        category="osint",
        description="SpiderFoot — automated OSINT collection framework",
        repo_url="https://github.com/smicallef/spiderfoot.git",
        install_type="git",
        entry_point="sf.py",
        launch_cmd=["python3", "{TOOL_DIR}/sf.py", "-l", "127.0.0.1:5001"],
        license="MIT",
        author="Steve Micallef",
        homepage="https://www.spiderfoot.net",
    ),
    Tool(
        name="theHarvester",
        category="osint",
        description="Email, domain, IP, URL OSINT from open sources",
        repo_url="https://github.com/laramies/theHarvester.git",
        install_type="git",
        entry_point="theHarvester.py",
        launch_cmd=["python3", "{TOOL_DIR}/theHarvester.py"],
        license="GPL-2.0",
        author="Christian Martorella",
        homepage="https://github.com/laramies/theHarvester",
    ),
    Tool(
        name="sherlock",
        category="osint",
        description="Hunt down social media accounts by username",
        repo_url="https://github.com/sherlock-project/sherlock.git",
        install_type="git",
        entry_point="sherlock/sherlock.py",
        launch_cmd=["python3", "{TOOL_DIR}/sherlock/sherlock.py"],
        license="MIT",
        author="Sherlock Project",
        homepage="https://github.com/sherlock-project/sherlock",
    ),
    Tool(
        name="maltego",
        category="osint",
        description="Maltego — link analysis and data mining (community edition)",
        repo_url="",
        install_type="manual",
        entry_point="maltego",
        launch_cmd=["maltego"],
        license="Proprietary (Community Edition free)",
        author="Paterva",
        homepage="https://www.maltego.com",
        notes="Download from maltego.com — requires registration",
    ),
    Tool(
        name="recon-ng",
        category="osint",
        description="Web reconnaissance framework with modular design",
        repo_url="https://github.com/lanmaster53/recon-ng.git",
        install_type="git",
        entry_point="recon-ng",
        launch_cmd=["python3", "{TOOL_DIR}/recon-ng"],
        license="GPL-3.0",
        author="Tim Tomes",
        homepage="https://github.com/lanmaster53/recon-ng",
    ),
    Tool(
        name="osint-framework",
        category="osint",
        description="OSINT Framework — categorized web-based tool index",
        repo_url="https://github.com/lockfale/osint-framework.git",
        install_type="git",
        entry_point="index.html",
        launch_cmd=["xdg-open", "{TOOL_DIR}/index.html"],
        license="MIT",
        author="Justin Nordine",
        homepage="https://osintframework.com",
    ),
    Tool(
        name="Photon",
        category="osint",
        description="Web crawler for OSINT — extracts URLs, emails, keys",
        repo_url="https://github.com/s0md3v/Photon.git",
        install_type="git",
        entry_point="photon.py",
        launch_cmd=["python3", "{TOOL_DIR}/photon.py"],
        license="GPL-3.0",
        author="s0md3v",
        homepage="https://github.com/s0md3v/Photon",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# CLOUD & CONTAINER FORENSICS
# ──────────────────────────────────────────────────────────────────────────────
CLOUD_TOOLS: list[Tool] = [
    Tool(
        name="cloudtrail-explorer",
        category="cloud",
        description="Explore and analyze AWS CloudTrail logs",
        repo_url="https://github.com/trufflesecurity/cloudtrail-explorer.git",
        install_type="git",
        entry_point="main.go",
        launch_cmd=["go", "run", "{TOOL_DIR}/main.go"],
        license="MIT",
        author="TruffleHog / Trufflsecurity",
        homepage="https://github.com/trufflesecurity/cloudtrail-explorer",
    ),
    Tool(
        name="trufflehog",
        category="cloud",
        description="Find leaked credentials in git repos / cloud storage",
        repo_url="https://github.com/trufflesecurity/trufflehog.git",
        install_type="binary",
        entry_point="trufflehog",
        launch_cmd=["{TOOL_DIR}/trufflehog"],
        license="AGPL-3.0",
        author="Truffle Security",
        homepage="https://github.com/trufflesecurity/trufflehog",
    ),
    Tool(
        name="pacu",
        category="cloud",
        description="AWS exploitation / forensics framework",
        repo_url="https://github.com/RhinoSecurityLabs/pacu.git",
        install_type="git",
        entry_point="pacu.py",
        launch_cmd=["python3", "{TOOL_DIR}/pacu.py"],
        license="BSD-3-Clause",
        author="Rhino Security Labs",
        homepage="https://github.com/RhinoSecurityLabs/pacu",
        notes="Use for authorized AWS forensics and incident response",
    ),
    Tool(
        name="docker-explorer",
        category="cloud",
        description="Docker forensics — explore container file systems",
        repo_url="https://github.com/google/docker-explorer.git",
        install_type="git",
        entry_point="docker_explorer.py",
        launch_cmd=["python3", "{TOOL_DIR}/docker_explorer.py"],
        license="Apache-2.0",
        author="Google",
        homepage="https://github.com/google/docker-explorer",
    ),
    Tool(
        name="aws-ir",
        category="cloud",
        description="AWS Incident Response toolkit",
        repo_url="https://github.com/ThreatResponse/aws_ir.git",
        install_type="git",
        entry_point="aws_ir/__main__.py",
        launch_cmd=["python3", "-m", "aws_ir"],
        license="Apache-2.0",
        author="ThreatResponse",
        homepage="https://github.com/ThreatResponse/aws_ir",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# REPORTING & CASE MANAGEMENT
# ──────────────────────────────────────────────────────────────────────────────
REPORTING_TOOLS: list[Tool] = [
    Tool(
        name="dfimagetools",
        category="reporting",
        description="dfImageTools — utility scripts for disk image workflows",
        repo_url="https://github.com/libyal/dfimagetools.git",
        install_type="git",
        entry_point="scripts/imaged_hash_file.py",
        launch_cmd=["python3", "{TOOL_DIR}/scripts/imaged_hash_file.py"],
        license="Apache-2.0",
        author="Joachim Metz",
        homepage="https://github.com/libyal/dfimagetools",
    ),
    Tool(
        name="timeline_lab",
        category="reporting",
        description="Timeline Lab — Excel-based timeline analysis",
        repo_url="https://github.com/certsocietegenerale/timeline-lab.git",
        install_type="git",
        entry_point="timeline_lab.py",
        launch_cmd=["python3", "{TOOL_DIR}/timeline_lab.py"],
        license="MIT",
        author="CERT Société Générale",
        homepage="https://github.com/certsocietegenerale/timeline-lab",
    ),
    Tool(
        name="dfvfs",
        category="reporting",
        description="Digital Forensics Virtual Filesystem — abstract layer for evidence",
        repo_url="https://github.com/log2timeline/dfvfs.git",
        install_type="pip",
        entry_point="dfvfs",
        launch_cmd=["python3", "-m", "dfvfs"],
        license="Apache-2.0",
        author="log2timeline contributors",
        homepage="https://github.com/log2timeline/dfvfs",
    ),
]

# ──────────────────────────────────────────────────────────────────────────────
# MASTER CATALOG
# ──────────────────────────────────────────────────────────────────────────────
ALL_TOOLS: list[Tool] = (
    MOBILE_ANDROID
    + MOBILE_IOS
    + DISK_TOOLS
    + MEMORY_TOOLS
    + LOG_TOOLS
    + NETWORK_TOOLS
    + ARTIFACT_TOOLS
    + PASSWORD_TOOLS
    + MALWARE_TOOLS
    + IR_TOOLS
    + OSINT_TOOLS
    + CLOUD_TOOLS
    + REPORTING_TOOLS
)

CATEGORIES: dict[str, list[Tool]] = {
    "Mobile (Android)": MOBILE_ANDROID,
    "Mobile (iOS/Apple)": MOBILE_IOS,
    "Disk & Imaging": DISK_TOOLS,
    "Memory": MEMORY_TOOLS,
    "Logs & Timeline": LOG_TOOLS,
    "Network": NETWORK_TOOLS,
    "Artifact Analysis": ARTIFACT_TOOLS,
    "Password & Hash": PASSWORD_TOOLS,
    "Malware & RE": MALWARE_TOOLS,
    "Incident Response": IR_TOOLS,
    "OSINT": OSINT_TOOLS,
    "Cloud & Container": CLOUD_TOOLS,
    "Reporting": REPORTING_TOOLS,
}

TOOL_BY_NAME: dict[str, Tool] = {t.name: t for t in ALL_TOOLS}
